apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: iopy5ity8-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/iopy5ity8-java-springboot-gitops